@startuml
actor Jugador
participant Juego
participant Jugador
participant Neutral
participant Mercado
participant ComprarCombustibleAccion
participant NaveAliada

Jugador -> Juego: iniciarJuego()
activate Juego
Juego -> Jugador: obtenerJugador()
activate Jugador
Jugador -> Neutral: realizarAccionEnMercado()
activate Neutral
Neutral -> Mercado: realizarAccion()
activate Mercado
loop Mientras haya acciones
    Mercado -> ComprarCombustibleAccion: realizar()
    activate ComprarCombustibleAccion
    ComprarCombustibleAccion -> NaveAliada: getCombustible()
    NaveAliada --> ComprarCombustibleAccion: combustibleActual
    alt Si combustibleActual es menor que 100
        ComprarCombustibleAccion -> Jugador: getUadeCoins()
        Jugador --> ComprarCombustibleAccion: uadeCoins
        ComprarCombustibleAccion -> NaveAliada: llenarTanqueDeCombustible()
        NaveAliada -> Jugador: quitarUadeCoins()
        Jugador --> NaveAliada: uadeCoinsActualizado
        NaveAliada --> ComprarCombustibleAccion: combustibleActualizado
        ComprarCombustibleAccion --> Mercado: mostrarMensaje()
    else Si combustibleActual es igual o mayor que 100
        ComprarCombustibleAccion --> Mercado: mostrarMensaje("Combustible lleno")
    end
    deactivate ComprarCombustibleAccion
end
deactivate Mercado
deactivate Neutral
deactivate Jugador
deactivate Juego
@enduml