@startuml
actor main
participant Juego
participant Neutral
main -> Juego: siguienteTurno(Acciones.VISITAR_PLANETA, "NEU-1")
activate Juego
Juego -> Neutral: visitarPlaneta("NEU-1")
activate Neutral
Neutral -> main: Planeta visitado
deactivate Neutral
Juego --> main: Acción completada
deactivate Juego
@enduml
