@startuml
actor main
participant Juego
participant Hostil

main -> Juego: siguienteTurno(BUSCAR_TESORO, "ENE-0")
activate Juego
Juego -> Juego: visitarPlaneta("ENE-0")
activate Juego
Juego -> Hostil: combate()
activate Hostil
Hostil --> Juego: boolean
deactivate Hostil
Juego -> Juego: finDelJuego(boolean naveDestruida, boolean tesoroEncontrado)
activate Juego
alt naveDestruida
    Juego -> main: Imprimir mensaje de nave destruida
    deactivate Juego
    main -> main: Salir del juego (Game Over)
else not naveDestruida
    alt tesoroEncontrado
        Juego -> main: Imprimir mensaje de tesoro encontrado
        deactivate Juego
        main -> main: Salir del juego (Victoria)
    else not tesoroEncontrado
        Juego -> main: Imprimir mensaje de no tesoro encontrado
        deactivate Juego
    end
end
deactivate Juego
@enduml
