@startuml
actor main

main -> Juego: siguienteTurno(Acciones accion, String codigoPlaneta)
activate Juego
Juego -> Juego: finDelJuego(boolean NaveDestruida, boolean TesoroEncontrado)
Juego -> planetaHostil : Combate(nave Nave, planeta PlanetaHostil)
activate planetaHostil
planetaHostil --> Juego : boolean
deactivate planetaHostil
opt Nave_enemiga_destruida
    Juego --> main : Tu nave fue destruida
    deactivate Juego
 Tu nave no fue destruida
    Juego --> main
end

@enduml
