@startuml
Main -> Controller : algunMetodoQueMeHagaMovermeEntrePlanetas(planeta)
activate Main
Controller -> Juego : algunMetodoQueMeHagaMovermeEntrePlanetas(planeta)
deactivate Main
activate Controller
Juego -> Jugador : viajeAPlaneta(planeta)
deactivate Controller
activate Juego

alt si el planeta no es el mismo en el que estoy
    Jugador -> Nave : getTanque()
    activate Jugador
    Nave -> Jugador : Tanque
    activate Nave
    Jugador -> Tanque : consumirCombustible()
    activate Tanque
    Tanque -> Tanque : setCombustible()
    Jugador -> Jugador : setPlanetaActual()
    Jugador -> Jugador : setPosicionEnElEspacio()
    deactivate Tanque
    deactivate Nave

else Si el planeta es el mismo no hace nada
    Jugador -> Jugador : nothing
    activate Jugador
    deactivate Jugador
end
@enduml

// hay muchos metodos que llaman a este para settear un planeta neutral,
pero no hay un metodo exclusivo de viajar a planeta nuetral, por eso llamo
a esos metodos que no existen desde el controller y el main.
