@startuml
participant Juego
participant Jugador
participant Neutral
participant Mercado
participant Nave

activate Juego
deactivate Juego
Juego -> Juego: siguienteTurno()
Juego -> Jugador: getPlanetaNeutral()
deactivate Juego
activate Jugador
Jugador -> Jugador: visitarPlanetaNeutral(planeta Planeta)
Jugador -> Neutral: getJugador()
deactivate Jugador
activate Neutral
Neutral -> Mercado: comerciar(jugador Jugador)
deactivate Neutral
activate Mercado

Mercado -> Nave: comprarEscudo(jugador Jugador)
activate Nave

Mercado -> Jugador: setUadeCoins(uadecoins float)
deactivate Mercado
activate Jugador
deactivate Jugador
Nave -> Nave: setEscudo()
@enduml
