@startuml
participant Juego
participant Jugador
participant Neutral


activate Juego
deactivate Juego
Juego -> Juego: siguienteTurno()
Juego -> Jugador: getPlanetaNeutral()
deactivate Juego
activate Jugador
Jugador -> Jugador: visitarPlanetaNeutral(planeta Planeta)
Jugador -> Neutral: getJugador()
deactivate Jugador
activate Neutral
@enduml
