@startuml
participant Juego
participant Jugador
participant Hostil
participant Nave
participant NavePirata

activate Juego
deactivate Juego
Juego -> Juego: siguienteTurno()
Juego -> Jugador: getPlanetaHostil()
deactivate Juego
activate Jugador
Jugador -> Jugador: visitarPlanetaHostil(planeta Planeta)
Jugador -> Hostil: getNave()
deactivate Jugador

activate Hostil
Hostil -> Hostil: combate(nave Nave)
alt pierde nave aliada
    activate NavePirata
    NavePirata -> Hostil: poderDeAtaque()
    deactivate NavePirata
    activate Nave
    Nave -> Hostil: poderDeAtaque()
    deactivate Nave
    activate NavePirata
    NavePirata -> Hostil: setVida()
    deactivate NavePirata
    activate Nave
    Nave -> Hostil: calcularDaño()
    destroy Nave
    deactivate Nave
else pierde nave enemiga
    activate NavePirata
    NavePirata -> Hostil: setVida()
    destroy NavePirata
    deactivate NavePirata
    activate Nave
    Nave -> Hostil: calcularDaño()
    deactivate Nave
    deactivate Hostil
end
@enduml

