

@startuml

'class Juego
Juego -- GestorDeJuego
Juego "1" o-- "1" Jugador

Jugador "1" o-- "*" Nave
GestorDeJuego -- Planeta
GestorDeJuego -- Nave

class GestorDeJuego{
- listaPlanetas: Lista Planetas
- navesDisponibles: Lista Naves
+ getPlaneta(): Planeta
+ getNave():Nave
}
class Juego {
    - turno: int
    - jugador: Jugador
    - gestor: GestorDeJuego
    + Juego(jugador Jugador)
    + siguienteTurno():Void
    + FinJuego(): Void
}

'class Jugador
class Jugador {
    - navesDelJugador: Lista Nave
    - nombre: string
    - uadecoins: double  ' Cantidad de Uadecoins del jugador
    + Jugador()
    + visitarPlaneta(planeta Planeta, nave Nave) : void
}

'class Nave

Nave -- Arma
Nave -- Escudo

abstract class Nave {
    - vida: double
    - velocidad: double
    - combustible: double
    - escudo: Escudo
    - arma: Arma

    + PoderAtaque(): double
    + calcularDaño(): double
}
'class Arma
class Arma {
    - nivel : int
    - poder: double
    + Arma(poder: double)

}

'class Escudo
class Escudo {
    - nivel: int
    - proteccion: double
    + Escudo(proteccion: double)
}
' Clase para Nave Aegis
class NaveAegis extends Nave{
    + isResistente(): boolean
}

' Clase para Nave Swift
class NaveSwift extends Nave {
    + isEvitable(): boolean
}
'class Enemigo
class Enemigo extends Nave {

    + Enemigo()
    + calcularRecompensa(): double
}

'class Planeta

Hostil -- Enemigo
Neutral -- NaveAegis
Neutral -- NaveSwift
Neutral -- Mercado

abstract class Planeta {
    - nombre: String
    - tipo : boolean
    + Planeta (nombre String, tipo bolean)
}

'class Mercado
class Neutral extends Planeta{
    - mercado: Mercado
    - navesDisponibles: Lista
    + AccionDeMercado(mercado Mercado)
}
Abstract class Mercado {
    uadecoins:double

}
class Venta extends Mercado{
    + venderNave(nave:Nave): void
}
class Compra extends Mercado{
    + comprarNave(nave:Nave): void
    +  comprarCombustible(nave: Nave):void
}
class Mejora extends Mercado{
    + mejorarEscudo(nave: Nave):
    + mejorarArma(nave: Nave):double
}

' Subclase de Planeta: Hostil
class Hostil extends Planeta{
    - tesoro : boolean
    - listaEnemigos: ListaEnemigos
    + combate(nave: Nave, enemigo: Enemigo):void
}


@enduml