@startuml
participant Juego
participant Jugador
participant Neutral
participant Mercado
participant NaveAliada

activate Juego
deactivate Juego
Juego -> Juego: siguienteTurno()
Juego -> Jugador: getPlanetaNeutral()
deactivate Juego
activate Jugador
Jugador -> Jugador: visitarPlanetaNeutral(planeta Planeta)
Jugador -> Neutral: getJugador()
deactivate Jugador
activate Neutral
Neutral -> Mercado: comerciar(jugador Jugador)
deactivate Neutral
activate Mercado

Mercado -> NaveAliada: comprarEscudo(jugador Jugador)
activate NaveAliada

Mercado -> Jugador: setUadeCoins(uadecoins float)
deactivate Mercado
activate Jugador
deactivate Jugador
NaveAliada -> NaveAliada: setEscudo()
@enduml
