@startuml
participant Juego
participant Jugador
participant Neutral
participant Mercado
participant NaveAliada

activate Juego
deactivate Juego
Juego -> Juego: siguienteTurno()
Juego -> Jugador: getPlanetaNeutral()
deactivate Juego
activate Jugador
Jugador -> Jugador: visitarPlanetaNeutral(planeta Planeta)
Jugador -> Neutral: getJugador()
deactivate Jugador
activate Neutral
Mercado <- Neutral : getMercado()
deactivate Neutral
activate Mercado




Mercado -> Mercado: comprarEscudo(cantDeEscudoAComprar float)
activate Jugador
Jugador -> Mercado: getUadeCoins();


Mercado -> Jugador: setUadeCoins(uadecoins doable)
deactivate Jugador
activate NaveAliada
Mercado -> NaveAliada: setEscudo(cantDeEscudoAComprar float) float)
deactivate Mercado
@enduml
